### ISSUE TITLE
오타 제보합니다.

### ISSUE THREAD

**Issue by juunone** [nhn/fe.javascript#48]
![스크린샷 2019-07-04 10 46 18](https://user-images.githubusercontent.com/35126809/60634199-198d4280-9e49-11e9-8eea-1eeb3449c599.png)

안녕하세요 문서를 보다가 오타 내용이 있어서 제보드립니다 ! 🙇‍♂️
https://ui.toast.com/fe-guide/ko/ 해당 페이지에서
위 스크린샷과 같이 '번들러' 와 'ES5 to ES6+' 내용이 같습니다.
감사합니다.

**Comment by seonim-ryu** [comment]
@juunone 
해당 부분은 수정하여 브랜드 사이트에 업데이트 되었습니다.
소중한 제보 감사합니다. 🙇‍♂️
