### ISSUE TITLE
안티패턴에 내용 수정 요청드립니다.

### ISSUE THREAD

**Issue by JUNWOO45** [nhn/fe.javascript#51]
https://ui.toast.com/fe-guide/ko_ANTI-PATTERN/
위 주소의 '변수 선언 없이 바로 변수를 사용하지 않는다' 파트인데요.

<img width="1193" alt="nhn" src="https://user-images.githubusercontent.com/40589483/63570717-0aa94d80-c5b9-11e9-838a-9fca5e15fef2.png">

const와 let은 호이스팅 되지않는다고 써있는데요.
const와 let도 블록스코프 단위로 호이스팅이 발생합니다.

```
var a = 'outer';
(function() {
  var a;
  console.log(a);
  a = 'inner';
})();
```

console에서 실행해보면, undefined이 2번 출력되는데,
첫번째는 변수선언과 변수초기화가 동시에 일어나는 var의 특성과 호이스팅으로 인해 출력되는 undefined이고,
두번째는 return이 없어서 출력되는 undefined입니다.

```
const b = 'outer';
(function() {
  console.log(b);
  const b = 'inner';
})();
```

console에서 실행해보면, ReferenceError가 발생하는데요.
호이스팅이 발생했고 변수 선언이 된 다음, 변수 초기화가 이루어지지않아서 생기는 에러입니다.

두가지 케이스의 비교를 통해서 const와 let도 호이스팅이 발생하는 것을 알 수 있습니다.

확인부탁드리겠습니다!
감사합니다.

**Comment by mitrvlr** [comment]
장황하게 설명하려했지만 글재주가 없어서 예전에 읽었던 [아티클의 링크](https://medium.com/korbit-engineering/let%EA%B3%BC-const%EB%8A%94-%ED%98%B8%EC%9D%B4%EC%8A%A4%ED%8C%85-%EB%90%A0%EA%B9%8C-72fcf2fac365)를 남깁니다. 

호이스팅이라는 개념이 난해하긴하죠..

**Comment by seonim-ryu** [comment]
@JUNWOO45 
안녕하세요. 먼저, fe.javascript 리포지터리가 브랜드 사이트로 대체 운영됨에 따라 깃헙 이슈 확인이 늦어진 점 양해 부탁드립니다.

> `const`와 `let` 키워드와 함께 선언한 변수는 블록 스코프(block-scoped)를 가지며 호이스팅되지 않는다.

문제로 제기해주신 문장을 살펴보면, 호이스팅 범위를 어디까지 보느냐에 따라 해석이 달라진 것 같습니다. `let` (또는 `const`) 키워드를 사용한 변수는 선언 전에 변수에 접근할 수 없고 변수가 선언되기 전까지 TDZ(Temporal dead zone)에 놓이게 됩니다. 우리는 이 경우를 호이스팅이 되지 않는다고 보았습니다. 현재 스펙 문서에서도 호이스팅을 명확하게 정의하고 있지 않다보니 이에 관해 의견이 분분한 것 같습니다.

결국 가이드에서 전달하려고 했던 내용은, **변수의 키워드 사용에 따라 변수에 접근할 수 있는 스코프가 달라지고 호이스팅 동작도 달라져 예상치 못한 문제가 발생할 수 있으니, 변수 초기화 전 반드시 변수 선언을 하고 사용해야한다는 점**이었습니다.

호이스팅이 된다/안된다의 어휘 사용 문제는 아니라고 보며, 해당 가이드의 문맥에 맞도록 다음과 같이 수정합니다.

> `const`와 `let` 키워드와 함께 선언한 변수는 블록 스코프(block-scoped)를 가지며 호이스팅에 의한 문제가 발생하지 않는다.

**Comment by JUNWOO45** [comment]
@seonim-ryu 
안녕하세요.
우선, 호이스팅에대한 다른 시각이 있음을 몰랐습니다.
그리고 또 답변을 읽는 와중 느낀 점이..
가이드를 읽고 이슈를 생성할 당시, 견월망지한 듯 하여 부끄럽네요 ;_;
답변주셔서 감사합니다.
