### ISSUE TITLE
Editor 링크가 깨졌습니다.

### ISSUE THREAD

**Issue by leechwin** [nhn/fe.javascript#52]
Applications > Editor > Documentation 항목의 API, Example,부분 링크가 유효하지 않은것 같습니다.(404에러)
- https://nhn.github.io/tui.editor/api/latest/
- https://nhn.github.io/tui.editor/api/latest/tutorial-example00-demo.html

**Comment by seonim-ryu** [comment]
@leechwin 
링크 수정되었습니다. 제보 감사합니다! :)
